#ifndef PCPD_MSG_SENSOR
#define PCPD_MSG_SENSOR

#include "tcnart_msgs/msg/Types.idl"
#include "tcnart_msgs/msg/CameraModel.idl"

module pcpd_msgs {
  module msg {

    enum CameraSensorTypesEnum {
        GENERIC_RGBD,
        KINECT_AZURE,
        FEMTO_MEGA
    };

    @verbatim (language="comment", text=
      "This represents a camera sensor connected to a pcpd instance.")
    struct CameraSensor {
      @verbatim (language="comment", text=
        "An camera sensor is a physical device like an Azure Kinect camera that captures measurements.")

      string name;

      string serial_number;

      CameraSensorTypesEnum camera_type;

      boolean depth_enabled;
      boolean color_enabled;
      boolean infrared_enabled;

      string depth_descriptor_topic;
      string infrared_descriptor_topic;
      tcnart_msgs::msg::CameraModel depth_parameters;

      string color_descriptor_topic;
      tcnart_msgs::msg::CameraModel color_parameters;

      tcnart_msgs::msg::RigidTransform camera_pose;
      // maybe not named correctly
      tcnart_msgs::msg::RigidTransform color2depth_transform; 

      uint32 frame_rate;

      sequence<octet> raw_calibration;

      float depth_units_per_meter;

      uint64 timestamp_offset_ns;

    };
  };
};

#endif
