#ifndef PCPD_MSG_TYPES
#define PCPD_MSG_TYPES

module pcpd_msgs {
  module msg {

    typedef float float__2[2];
    typedef float float__3[3];
    typedef float float__4[4];
    typedef float float__9[9];
    typedef float float__12[12];
    typedef float float__16[16];

    struct ApiVersion {
        uint32 major;
        uint32 minor;
        uint32 patch;
    };

  };
};

#endif
