#ifndef DEVICE_ORBBEC_RPC_MANAGER
#define DEVICE_ORBBEC_RPC_MANAGER

#include "device_orbbec_msgs/msg/OrbbecTypes.idl"

module device_orbbec_msgs {
  module rpc {

    struct RPCMGRRequest_StartOrbbecCamera {
        boolean enable_streaming;
        boolean enable_encoding;
        boolean enable_tracking;

        boolean enable_color;
        boolean enable_depth;
        boolean enable_ir;
        boolean enable_accel;
        boolean enable_gyro;

        device_orbbec_msgs::msg::enums::AlignMode align_mode;

        device_orbbec_msgs::msg::enums::DeviceConnectionType connection_type;
        string device_identifier;

        device_orbbec_msgs::msg::VideoStreamProfile color_stream;
        device_orbbec_msgs::msg::VideoStreamProfile depth_stream;
        device_orbbec_msgs::msg::VideoStreamProfile ir_stream;
        device_orbbec_msgs::msg::AccelStreamProfile accel_stream;
        device_orbbec_msgs::msg::GyroStreamProfile gyro_stream;

        device_orbbec_msgs::msg::MultiDeviceSyncConfig device_sync;

    };


        };
};

#endif