#ifndef DEVICE_HL2_RPC_HL2MANAGER
#define DEVICE_HL2_RPC_HL2MANAGER

#include "device_hl2_msgs/msg/Hololens2Enums.idl"
#include "tcnart_msgs/msg/Types.idl"
#include "tcnart_msgs/rpc/GenericManager.idl"

module device_hl2_msgs {
  module rpc {

    struct HL2MGRRequest_StartRM {
      boolean enable_location;
      boolean enable_left_front;
      boolean enable_left_left;
      boolean enable_right_front;
      boolean enable_right_right;
      tcnart_msgs::rpc::RPCMGR_H26xFormat vlc_format;
      tcnart_msgs::rpc::RPCMGR_TrackerConfig vlc_tracker_config;

      boolean enable_depth_ahat;
      boolean enable_depth_long_throw;
      tcnart_msgs::rpc::RPCMGR_H26xFormat depth_format;
      tcnart_msgs::rpc::RPCMGR_TrackerConfig depth_tracker_config;

      boolean enable_imu_accel;
      boolean enable_imu_gyro;
      boolean enable_imu_mag;
    };

    struct HL2MGRRequest_StartPV {
      boolean enable_location;
      boolean enable_streaming;
      boolean enable_encoding;
      boolean enable_tracking;

      int32 device_id;
      
      tcnart_msgs::rpc::RPCMGR_H26xFormat video_format;
      tcnart_msgs::rpc::RPCMGR_TrackerConfig tracker_config;
    };

    struct HL2MGRRequest_StartMC {
      tcnart_msgs::rpc::RPCMGR_AACFormat aac_format;
    };


  };
};

#endif