#ifndef DEVICE_HL2_RPC_HL2SPATIALMAPPING
#define DEVICE_HL2_RPC_HL2SPATIALMAPPING

#include "tcnart_msgs/rpc/Requests.idl"
#include "tcnart_msgs/msg/Types.idl"
#include "device_hl2_msgs/msg/Enums.idl"

module device_hl2_msgs {
  module rpc {

    enum HL2SpatialMapping_VolumeType {
      SM_VT_BOX,
      SM_VT_FRUSTUM,
      SM_VT_ORIENTED_BOX,
      SM_VT_SPHERE
    };


    struct HL2SpatialMapping_SurfaceInfo {
      tcnart_msgs::msg::MSGuid id;
      int64 update_time;
    };


    struct HL2SpatialMapping_MeshDescription {
      tcnart_msgs::msg::MSGuid id;
      double maxtpcm;
      uint32 vertex_format;
      uint32 triangle_format;
      uint32 normal_format;
      uint32 flags;
    };

    struct HL2SpatialMapping_MeshInfo {
      uint32 index;
      uint32 status;
      uint32 vpl;
      uint32 til;
      uint32 vnl;
      tcnart_msgs::msg::Vector3 scale;
      tcnart_msgs::msg::Vector3 position;
      tcnart_msgs::msg::Quaternion orientation;
      uint32 bsz;
      tcnart_msgs::msg::OrientedBox bounds;
      sequence<uint8> vpd;
      sequence<uint8> tid;
      sequence<uint8> vnd;
    };

    union HL2SpatialMapping_Volume switch(HL2SpatialMapping_VolumeType) {
      case SM_VT_BOX:
        tcnart_msgs::msg::BoundingBox bounding_box;
      case SM_VT_FRUSTUM:
        tcnart_msgs::msg::Frustum frustum;
      case SM_VT_ORIENTED_BOX:
        tcnart_msgs::msg::OrientedBox oriented_box;
      case SM_VT_SPHERE:
        tcnart_msgs::msg::Sphere sphere;
    };

    struct HL2SMRequest_SetVolumes {
      sequence<HL2SpatialMapping_Volume> volumes;
    };

    struct HL2SMResponse_GetObservedSurfaces {
      sequence<HL2SpatialMapping_SurfaceInfo> surfaces;
      tcnart_msgs::rpc::RPCResponseStatus status;
    };


    struct HL2SMRequest_GetMeshes {
      uint32 max_tasks;
      sequence<HL2SpatialMapping_MeshDescription> description;
    };

    struct HL2SMResponse_GetMeshes {
      sequence<HL2SpatialMapping_MeshInfo> meshes;
      tcnart_msgs::rpc::RPCResponseStatus status;
    };



  };
};

#endif