#ifndef DEVICE_HL2_RPC_HL2VOICEINPUT
#define DEVICE_HL2_RPC_HL2VOICEINPUT

#include "tcnart_msgs/rpc/Types.idl"
#include "device_hl2_msgs/rpc/Types.idl"

module device_hl2_msgs {
  module rpc {

    struct HL2VIVoiceInput_Result {
      uint32 index;
      uint32 confidence;
      uint64 phrase_duration;
      uint64 phrase_start_time;
      double raw_confidence;
    };

    struct HL2VIRequest_RegisterCommands {
      boolean clear;
      sequence<string> commands;
    };

    struct HL2VIResponse_VoiceInput_Pop {
      sequence<HL2VIVoiceInput_Result> results;
      tcnart_msgs::rpc::RPCResponseStatus status;
    };



  };
};

#endif