#ifndef DEVICE_HL2_RPC_HL2MANAGER
#define DEVICE_HL2_RPC_HL2MANAGER

#include "device_hl2_msgs/msg/Types.idl"

module device_hl2_msgs {
  module rpc {

    struct HL2MGR_H26xFormat {
      uint16 width;
      uint16 height;
      uint8 frame_rate;
      device_hl2_msgs::msg::enums::Hololens2H26xProfile profile;
      uint32 bitrate;
    };

    struct HL2MGR_AACFormat {
      uint32 channels;
      uint32 sample_rate;
      device_hl2_msgs::msg::enums::Hololens2AACProfile profile;
    };

    struct HL2MGRRequest_StartRM {
      boolean enable_location;
      boolean enable_left_front;
      boolean enable_left_left;
      boolean enable_right_front;
      boolean enable_right_right;
      HL2MGR_H26xFormat vlc_format;

      boolean enable_depth_ahat;
      boolean enable_depth_long_throw;
      HL2MGR_H26xFormat depth_format;

      boolean enable_imu_accel;
      boolean enable_imu_gyro;
      boolean enable_imu_mag;
    };

    struct HL2MGRRequest_StartPV {
      boolean enable_location;
      HL2MGR_H26xFormat pv_format;
    };

    struct HL2MGRRequest_StartMC {
      HL2MGR_AACFormat aac_format;
    };


  };
};

#endif