// SPDX-License-Identifier: internal
//
// Minimal stand-ins for the generated `tcnart_msgs` types, and a codec over
// them.
//
// These are **definitions of types the library only forward-declares**, which
// is the point: if `wire_type.h` or `session.h` needed anything more than a
// declaration, this file would not compile and the "dependency-free" claim
// would be false. It also means the whole test suite builds on a machine with
// no fastddsgen and no Java.
//
// They are not tested. The real ones are generated by fastdds-gen and are
// assumed correct; asserting on generated accessors would test the generator.
// What is tested here is *this library's* logic over them.
#ifndef TCN_SQE_TEST_STUB_MSGS_H
#define TCN_SQE_TEST_STUB_MSGS_H

#include <cstdint>
#include <string>
#include <vector>

#include "tcn/sqe/handle.h"
#include "tcn/sqe/result.h"
#include "tcn/sqe/transport.h"

namespace tcnart_msgs {
namespace rpc {

class SISJoinRequest
{
public:
    std::string graph_origin;
};

class SISLeaveRequest
{
public:
    std::string client;
};

class SISNodeUpdateRequest
{
public:
    std::string name;
};

class SISEdgeUpdateRequest
{
public:
    std::string name;
};

class SISRelationStreamStartRequest
{
public:
    std::string observer;
    std::string target;
};

class SISRelationStreamStopRequest
{
public:
    std::string handle;
};

/// Shaped like the generated union: the case accessor is only correct to touch
/// once the discriminator has been read.
class SISRelationStreamHandleUnion
{
public:
    std::int32_t d = 0;
    std::string topic_;

    std::int32_t _d() const { return d; }
    const std::string& topic() const { return topic_; }
};

class SISRelationStreamReply
{
public:
    std::int32_t status_ = 0;
    SISRelationStreamHandleUnion handle_;

    std::int32_t status() const { return status_; }
    const SISRelationStreamHandleUnion& handle() const { return handle_; }
};

}  // namespace rpc
}  // namespace tcnart_msgs

namespace tcn {
namespace sqe {
namespace test {

/// A codec of the shape `SisSession` asks for.
///
/// It does not serialise anything realistic — CDR is FastCDR's job and testing
/// it would test FastCDR. It writes a recognisable marker so a test can assert
/// that the bytes on the wire came from the request it was given, and it can be
/// told to fail so the encode/decode error paths are exercised.
struct StubCodec
{
    static bool encode_fails;
    static bool decode_fails;
    static std::string last_decoded_marker;

    template <class T>
    static Result<void> encode(const T&, std::vector<std::uint8_t>& out)
    {
        if (encode_fails) { return Result<void>::fail(Error::EncodeFailed); }
        const char* marker = "STUB";
        out.assign(marker, marker + 4);
        return Result<void>::ok();
    }

    template <class T>
    static Result<void> decode(BytesView, T&)
    {
        if (decode_fails) { return Result<void>::fail(Error::DecodeFailed); }
        return Result<void>::ok();
    }
};

inline bool StubCodec::encode_fails = false;
inline bool StubCodec::decode_fails = false;
inline std::string StubCodec::last_decoded_marker;

/// Builds a reply the way the engine would.
inline ::tcnart_msgs::rpc::SISRelationStreamReply make_reply(Status s, const char* topic)
{
    ::tcnart_msgs::rpc::SISRelationStreamReply r;
    r.status_ = static_cast<std::int32_t>(s);
    if (carries_handle(s))
    {
        r.handle_.d = kHandleKindAssigned;
        r.handle_.topic_ = topic;
    }
    else
    {
        r.handle_.d = kHandleKindNone;
    }
    return r;
}

/// A `Handle` for a topic, obtained the only way there is: from a reply.
inline Handle handle_for(const char* topic)
{
    return Handle::from_reply(make_reply(Status::Active, topic)).value();
}

}  // namespace test
}  // namespace sqe
}  // namespace tcn

#endif  // TCN_SQE_TEST_STUB_MSGS_H
