#ifndef TCNART_RPC_TYPES
#define TCNART_RPC_TYPES

module tcnart_msgs {
  module rpc {

    enum RPCResponseStatus {
      RPC_STATUS_SUCCESS,
      RPC_STATUS_ERROR
    };


    // null
    struct NullRequest {
        uint8 dummy;
    };

    struct NullReply {
        RPCResponseStatus status;
    };

    // string
    struct StringRequest {
        string value;
    };

    struct StringReply {
        string value;
        RPCResponseStatus status;
    };


    // bool
    struct BoolRequest {
        boolean value;
    };

    struct BoolReply {
        boolean value;
        RPCResponseStatus status;
    };

    // uint32
    struct UInt32Request {
        uint32 value;
    };

    struct UInt32Reply {
        uint32 value;
        RPCResponseStatus status;
    };

    // uint64
    struct UInt64Request {
        uint64 value;
    };

    struct UInt64Reply {
        uint64 value;
        RPCResponseStatus status;
    };


    // int32
    struct Int32Request {
        int32 value;
    };

    struct Int32Reply {
        int32 value;
        RPCResponseStatus status;
    };

    // int64
    struct Int64Request {
        int64 value;
    };

    struct Int64Reply {
        int64 value;
        RPCResponseStatus status;
    };


    // float32
    struct Float32Request {
        float value;
    };

    struct Float32Reply {
        float value;
        RPCResponseStatus status;
    };
    
    // float64
    struct Float64Request {
        double value;
    };

    struct Float64Reply {
        double value;
        RPCResponseStatus status;
    };


  };
};

#endif
