#ifndef TCNART_RPC_TYPES
#define TCNART_RPC_TYPES

module tcnart_msgs {
  module rpc {

    enum RPCResponseStatus {
      RPC_STATUS_SUCCESS,
      RPC_STATUS_ERROR
    };


    // null
    struct NullRequest {
        uint8 dummy;
    };

    struct NullReply {
        RPCResponseStatus status;
    };

    // string
    struct StringRequest {
        string value;
    };

    struct StringReply {
        string value;
        RPCResponseStatus status;
    };


    // bool
    struct BoolRequest {
        boolean value;
    };

    struct BoolReply {
        boolean value;
        RPCResponseStatus status;
    };

    // uint32
    struct UInt32Request {
        uint32 value;
    };

    struct UInt32Reply {
        uint32 value;
        RPCResponseStatus status;
    };

    // uint64
    struct UInt64Request {
        uint64 value;
    };

    struct UInt64Reply {
        uint64 value;
        RPCResponseStatus status;
    };


    // int32
    struct Int32Request {
        int32 value;
    };

    struct Int32Reply {
        int32 value;
        RPCResponseStatus status;
    };

    // int64
    struct Int64Request {
        int64 value;
    };

    struct Int64Reply {
        int64 value;
        RPCResponseStatus status;
    };


    // float32
    struct Float32Request {
        float value;
    };

    struct Float32Reply {
        float value;
        RPCResponseStatus status;
    };
    
    // float64
    struct Float64Request {
        double value;
    };

    struct Float64Reply {
        double value;
        RPCResponseStatus status;
    };

    struct StringListRequest {
      sequence<string> values;
    };

    struct StringListReply {
      sequence<string> values;
      RPCResponseStatus status;
    };



    // Generic Parameter Interface
    enum ParameterValueType {
      PVT_STRING,
      PVT_INT32,
      PVT_INT64,
      PVT_FLOAT,
      PVT_DOUBLE,
      PVT_BOOL,
      PVT_STRUCT
    };

    struct Parameter;
    union ParameterValue;
    struct ParameterList;


    struct ParameterList {
        sequence<Parameter> parameters;
    };

    struct Parameter {
        string key;
        ParameterValue value;
    };

    union ParameterValue switch(ParameterValueType) {
    case PVT_STRING:
        string string_value;
    case PVT_INT32:
        int32 int32_value;
    case PVT_INT64:
        int64 int64_value;
    case PVT_FLOAT:
        float float_value;
    case PVT_DOUBLE:
        double double_value;
    case PVT_BOOL:
        boolean bool_value;
    case PVT_STRUCT:
        ParameterList struct_value;
    };

    struct ParameterSchema {
        string key;
        ParameterValueType value_type;
        sequence<ParameterValue> valid_entries;
    };

    struct ParameterListSchema {
        sequence<ParameterSchema> parameters;
    };


    // generic
    struct GenericParameterRequest {
        ParameterList value;
    };

    struct GenericParameterReply {
        ParameterList value;
        RPCResponseStatus status;
    };

    struct ParameterSchemaReply {
        ParameterListSchema schema;
        RPCResponseStatus status;
    };

  };
};

#endif
