#ifndef DEVICE_HL2_MSG_HL2AUDIO
#define DEVICE_HL2_MSG_HL2AUDIO

#include "device_hl2_msgs/msg/Enums.idl"
#include "std_msgs/msg/Header.idl"
#include "tcnart_msgs/msg/Types.idl"

module device_hl2_msgs {
  module msg {

    struct Hololens2AudioStream {

      std_msgs::msg::Header header;

      tcnart_msgs::msg::AudioAACProfile profile;

      uint64 data_size;
      sequence<uint8> data;

    };
  };
};
#endif