#ifndef DEVICE_HL2_MSG_HL2VIDEO
#define DEVICE_HL2_MSG_HL2VIDEO

#include "tcnart_msgs/msg/Types.idl"
#include "device_hl2_msgs/msg/Types.idl"
#include "std_msgs/msg/Header.idl"
#include "geometry_msgs/msg/Vector3.idl"
#include "geometry_msgs/msg/Quaternion.idl"

module device_hl2_msgs {
  module msg {

    struct Hololens2VideoStream {

      std_msgs::msg::Header header;

      geometry_msgs::msg::Vector3 position;
      geometry_msgs::msg::Quaternion orientation;

      tcnart_msgs::msg::float__2 camera_focal_length;
      tcnart_msgs::msg::float__2 camera_principal_point;
      
      tcnart_msgs::msg::float__3 camera_radial_distortion;
      tcnart_msgs::msg::float__2 camera_tangential_distortion;

      uint64 image_bytes;
      sequence<uint8> image;

    };
  };
};
#endif