#include "device_hl2_msgs/msg/Types.idl"
#include "std_msgs/msg/Header.idl"

module device_hl2_msgs {
  module msg {

    struct Hololens2AudioStream {

      std_msgs::msg::Header header;

      Hololens2AACProfile profile;

      uint64 data_size;
      sequence<uint8> data;

    };
  };
};
