#ifndef DEVICE_HL2_MSG_HL2EYETRACKING
#define DEVICE_HL2_MSG_HL2EYETRACKING

#include "tcnart_msgs/msg/Types.idl"
#include "device_hl2_msgs/msg/Enums.idl"
#include "std_msgs/msg/Header.idl"

module device_hl2_msgs {
  module msg {

    struct Hololens2EyeTracking {

      std_msgs::msg::Header header;
      
      tcnart_msgs::msg::RigidTransform viewpoint;

      tcnart_msgs::msg::Ray center;
      tcnart_msgs::msg::Ray left_eye;
      tcnart_msgs::msg::Ray right_eye;
      
      float left_openness;
      float right_openness;
      
      float vergence_distance;
      uint32 valid;
    };
  };
};

#endif
