#ifndef DEVICE_HL2_MSG_HL2SENSORINFO
#define DEVICE_HL2_MSG_HL2SENSORINFO

#include "tcnart_msgs/msg/Types.idl"
#include "device_hl2_msgs/msg/Enums.idl"
#include "std_msgs/msg/Header.idl"

module device_hl2_msgs {
  module msg {

    struct Hololens2SensorInfoVLC {

      std_msgs::msg::Header header;

      sequence<float> uv2x;
      sequence<float> uv2y;

      sequence<float> mapx;
      sequence<float> mapy;

      float K[4];

      tcnart_msgs::msg::RigidTransform pose;
    };


    struct Hololens2SensorInfoZHT {

      std_msgs::msg::Header header;

      float scale;
      float alias;

      sequence<float> uv2x;
      sequence<float> uv2y;

      sequence<float> mapx;
      sequence<float> mapy;

      float K[4];

      tcnart_msgs::msg::RigidTransform pose;
    };


    struct Hololens2SensorInfoZLT {

      std_msgs::msg::Header header;

      float scale;

      sequence<float> uv2x;
      sequence<float> uv2y;

      sequence<float> mapx;
      sequence<float> mapy;

      float K[4];

      tcnart_msgs::msg::RigidTransform pose;
    };


    struct Hololens2ImuAccel {

      std_msgs::msg::Header header;

      uint64 vinyl_hup_ticks;
      uint64 soc_ticks;
      float values[3];
      float temperature;

      tcnart_msgs::msg::RigidTransform pose;
    };


    struct Hololens2ImuGyro {

      std_msgs::msg::Header header;
      
      uint64 vinyl_hup_ticks;
      uint64 soc_ticks;
      float values[3];
      float temperature;

      tcnart_msgs::msg::RigidTransform pose;
    };


    struct Hololens2ImuMag {

      std_msgs::msg::Header header;

      uint64 vinyl_hup_ticks;
      uint64 soc_ticks;
      float values[3];

      tcnart_msgs::msg::Vector3 position;
      tcnart_msgs::msg::Quaternion orientation;
    };

  };
};

#endif
