#ifndef DEVICE_HL2_MSG_HANDTRACKING
#define DEVICE_HL2_MSG_HANDTRACKING

#include "tcnart_msgs/msg/Types.idl"
#include "device_hl2_msgs/msg/Enums.idl"
#include "std_msgs/msg/Header.idl"

module device_hl2_msgs {
  module msg {

    enum Hololens2JointPoseAccuracy {
      High,
      Approximate
    };

    struct Hololens2HandJointPose {
      tcnart_msgs::msg::Quaternion orientation;
      tcnart_msgs::msg::Vector3 position;
      float radius;
      Hololens2JointPoseAccuracy accuracy;
    };

    struct Hololens2HandTracking {

      std_msgs::msg::Header header;

      tcnart_msgs::msg::Vector3 head_position;
      tcnart_msgs::msg::Vector3 head_forward;
      tcnart_msgs::msg::Vector3 head_up;

      tcnart_msgs::msg::Vector3 gaze_origin;
      tcnart_msgs::msg::Vector3 gaze_direction;
      
      sequence<Hololens2HandJointPose> left_poses;
      sequence<Hololens2HandJointPose> right_poses;

      uint8 valid;

    };
  };
};

#endif
