#ifndef TCNART_MSG_AUDIOSTREAM
#define TCNART_MSG_AUDIOSTREAM

#include "std_msgs/msg/Header.idl"
#include "tcnart_msgs/msg/Types.idl"

module tcnart_msgs {
  module msg {

    struct AudioStreamMessage {

      std_msgs::msg::Header header;

      uint32 sequence_id;
      string source_id;

      AudioEncoding encoding;
      AudioChannelLayout channel_layout;

      uint32 sample_rate_hz;
      uint32 channel_count;
      uint32 frames_per_chunk;

      float rms;
      float peak;

      uint64 data_size;
      sequence<uint8> data;

    };
  };
};
#endif
