#ifndef TCNART_MSG_CAMERA_CALIBRATION
#define TCNART_MSG_CAMERA_CALIBRATION

#include "std_msgs/msg/Header.idl"

module tcnart_msgs {
  module msg {

      // CAMERA_MODEL_SIMPLE_PINHOLE,
      // CAMERA_MODEL_SIMPLE_RADIAL,
      // CAMERA_MODEL_SIMPLE_RADIAL_FISHEYE,
      // CAMERA_MODEL_RADIAL,
      // CAMERA_MODEL_RADIAL_FISHEYE,
      // CAMERA_MODEL_OPEN_CV_FISHEYE,
      // CAMERA_MODEL_FOV,
      // CAMERA_MODEL_THIN_PRISM_FISHEYE,

    enum CameraModelType {
      CAMERA_MODEL_NONE,
      CAMERA_MODEL_PINHOLE,
      CAMERA_MODEL_OPEN_CV,
      CAMERA_MODEL_FULL_OPEN_CV,
      CAMERA_MODEL_SENSOR_AZURE_KINECT
    };

    struct CameraModel {

      CameraModelType camera_model;
      
      uint16 image_width;
      uint16 image_height;

      double focal_length[2];
      double principal_point[2];

      double tangential_coefficients[2];
      double radial_coefficients[8];

      // probably there are some fields missing to support all camera modesl -- see colmap for more detailed camera model
      
      // column major
      // float raw_matrix[16];

    };

    struct CameraInfoMessage {

      std_msgs::msg::Header header;

      CameraModel value;

    };


  };
};

#endif