#ifndef TCNART_MSG_HANDTRACKING
#define TCNART_MSG_HANDTRACKING

#include "tcnart_msgs/msg/Types.idl"
#include "std_msgs/msg/Header.idl"

module tcnart_msgs {
  module msg {

    enum JointPoseAccuracy {
      JointPoseAccuracy_High,
      JointPoseAccuracy_Approximate
    };

    struct HandJointPose {
      RigidTransform pose;
      float radius;
      JointPoseAccuracy accuracy;
    };

    struct HandState {
      Handedness hand;
      boolean tracked;
      boolean aim_valid;
      Ray aim;
      sequence<HandJointPose> joints;
    };

    struct HandTrackingMessage {

      std_msgs::msg::Header header;

      ViewPose head_pose;
      boolean gaze_valid;
      Ray gaze;
      sequence<HandState> hands;

    };
  };
};

#endif
