#ifndef TCNART_MSG_POSE_TRACKING
#define TCNART_MSG_POSE_TRACKING

#include "std_msgs/msg/Header.idl"
#include "tcnart_msgs/msg/Types.idl"

module tcnart_msgs {
  module msg {

    enum CameraModelType {
      CAMERA_MODEL_NONE,
      CAMERA_MODEL_SIMPLE_PINHOLE,
      CAMERA_MODEL_PINHOLE,
      CAMERA_MODEL_SIMPLE_RADIAL,
      CAMERA_MODEL_SIMPLE_RADIAL_FISHEYE,
      CAMERA_MODEL_RADIAL,
      CAMERA_MODEL_RADIAL_FISHEYE,
      CAMERA_MODEL_OPEN_CV,
      CAMERA_MODEL_OPEN_CV_FISHEYE,
      CAMERA_MODEL_FULL_OPEN_CV,
      CAMERA_MODEL_FOV,
      CAMERA_MODEL_THIN_PRISM_FISHEYE,
      CAMERA_MODEL_SENSOR_AZURE_KINECT,
    };

    enum MarkerType {
      MARKER_TYPE_NONE,
      MARKER_TYPE_ARUCO_MARKER,
      MARKER_TYPE_ARUCO_BOARD,
      MARKER_TYPE_ARUCO_FRACTAL,
      MARKER_TYPE_IR_TARGET
    };


    union TrackerConfigDetail  switch(MarkerType) {
      CASE MARKER_TYPE_NONE:

      CASE MARKER_TYPE_ARUCO_MARKER:
        string dictionary_id;    

      CASE MARKER_TYPE_ARUCO_BOARD:
        string dictionary_id;    

      CASE MARKER_TYPE_ARUCO_FRACTAL:
        string dictionary_id;    

      CASE MARKER_TYPE_IR_TARGET:

    };


    struct ArucoMarkerTargetConfig {
      float marker_size;
    };

    struct ArucoBoardTargetConfig {
      float marker_size;
    };

    struct ArucoFractalTargetConfig {
      float marker_size;
    };

    struct IRTargetConfig {
      sequence<Vector3> sphere_positions;
      float sphere_radius;

      uint8 min_visible_spheres;

      float lowpass_position;
      float lowpass_orientation;
    };


    union TrackingTargetConfig switch(MarkerType) {

      CASE MARKER_TYPE_ARUCO_MARKER:
        ArucoMarkerTargetConfig aruco_marker_config;

      CASE MARKER_TYPE_ARUCO_BOARD:
        ArucoBoardTargetConfig aruco_board_config;

      CASE MARKER_TYPE_ARUCO_FRACTAL:
        ArucoFractalTargetConfig aruco_fractal_config;

      CASE MARKER_TYPE_IR_TARGET:
        IRTargetConfig ir_config;

    };


    struct TrackerConfig {

      uint32 tracker_id;
      string tracker_name;

      MarkerType marker_type;
      TrackerConfigDetail config;

      sequence<TrackingTargetConfig> known_targets;

    };


    struct DetectedMarker {

      uint32 marker_id;

      RigidTransform pose;

    };


    struct DetectedMarkers {

      std_msgs::msg::Header header;

      sequence<DetectedMarker> poses;

    };

    struct ViewpointPose {

      std_msgs::msg::Header header;

      RigidTransform pose;

    }

  };
};

#endif