#ifndef TCNART_MSG_PRESENCE
#define TCNART_MSG_PRESENCE

#include "std_msgs/msg/Header.idl"

module tcnart_msgs {
  module msg {

    struct ServiceInfo {
        string service_name;
        string topic_prefix;
        string service_info;
    };

    struct TcnartPresenceMessage {
        std_msgs::msg::Header header;

        uint64 heart_beat_counter;

        sequence<ServiceInfo> services;
    };

  };
};

#endif