#ifndef TCNART_MSG_SRG
#define TCNART_MSG_SRG

#include "tcnart_msgs/msg/Types.idl"

module tcnart_msgs {
  module msg {

        enum SRNodeType {
          SRG_NODE_NONE,
          SRG_NODE_GENERIC,
          SRG_NODE_SENSOR,
          SRG_NODE_DISPLAY,
          SRG_NODE_TRACKABLE,
          SRG_NODE_CONTENT
        };

        enum SREdgeTemporalType {
          SRG_EDGE_TEMPORAL_NONE,
          SRG_EDGE_TEMPORAL_STATIC,
          SRG_EDGE_TEMPORAL_STATIC_CALIBRATED,
          SRG_EDGE_TEMPORAL_DYNAMIC,
          SRG_EDGE_TEMPORAL_DYNAMIC_INFERRED
        };

        enum CoordinateAxis {
            X,
            XNegative,
            Y,
            YNegative,
            Z,
            ZNegative
        };

        struct CoordinateSystem {
            CoordinateAxis forward;
            CoordinateAxis right;
            CoordinateAxis up;
            int8 dimensions;
        };

        struct SRNode {

            SRNodeType node_type;
            UUID node_uuid;
            uint32 node_id;
            string node_name;

            string custom_data;

        };

        struct SREdge {

            string edge_name;

            uint32 node_source_id;
            uint32 node_destination_id;

            SREdgeTemporalType temporal_type;

            string data_type;
            string uri;
        };

        struct SRGraph {

            string graph_name;

            sequence<SRNode> nodes;
            sequence<SREdge> edges;

        };
    };
};
#endif