#ifndef TCNART_MSG_SRG
#define TCNART_MSG_SRG

#include "tcnart_msgs/msg/Types.idl"

module tcnart_msgs {
  module msg {

        enum SRNodeType {
          SRG_NODE_NONE,
          SRG_NODE_GENERIC,
          SRG_NODE_SENSOR,
          SRG_NODE_DISPLAY,
          SRG_NODE_TRACKABLE,
          SRG_NODE_CONTENT
        };

        enum SREdgeDataType {
          SRG_EDGE_TYPE_NONE,
          SRG_EDGE_TYPE_POSE_6D,
          SRG_EDGE_TYPE_POSITION_3D,
          SRG_EDGE_TYPE_ORIENTATION_3D,
          SRG_EDGE_TYPE_POSITON_2D,
          SRG_EDGE_TYPE_ORIENTATION_2D,
          SRG_EDGE_TYPE_DISTANCE_1D,
          SRG_EDGE_TYPE_PROJECT_3D_TO_2D,
          SRG_EDGE_TYPE_PROJECT_2D_TO_3D
        };

        enum SREdgeTemporalType {
          SRG_EDGE_TEMPORAL_NONE,
          SRG_EDGE_TEMPORAL_STATIC,
          SRG_EDGE_TEMPORAL_STATIC_CALIBRATED,
          SRG_EDGE_TEMPORAL_DYNAMIC,
          SRG_EDGE_TEMPORAL_DYNAMIC_INFERRED
        };



        struct SRNode {

            SRNodeType node_type;
            UUID node_uuid;
            uint32 node_id;
            string node_name;

            string custom_data;
        
        };

        union SREdgeData switch(SREdgeDataType) {

          case SRG_EDGE_TYPE_POSE_6D:
            RigidTransform transform_6d;

          case SRG_EDGE_TYPE_POSITION_3D:
            Vector3 translation_3d;

          case SRG_EDGE_TYPE_ORIENTATION_3D:
            Quaternion rotation_3d;

          case SRG_EDGE_TYPE_POSITON_2D:
            Vector2 translation_2d;

          case SRG_EDGE_TYPE_ORIENTATION_2D:
            // in radian
            double rotation_2d;

          case SRG_EDGE_TYPE_DISTANCE_1D:
            double translation_1d;

          //case SRG_EDGE_TYPE_NONE:
          //case SRG_EDGE_TYPE_PROJECT_3D_TO_2D:
          //case SRG_EDGE_TYPE_PROJECT_2D_TO_3D:


        };

        struct SREdge {

            string edge_name;

            uint32 node_source_id;
            uint32 node_destination_id;

            SREdgeTemporalType temporal_type;

            SREdgeDataType data_type;
            SREdgeData transform;
        
        };

        // complete missing Types: 1D, 2d3d, 3d2d

        struct SRGraph {

            string graph_name;

            sequence<SRNode> nodes;
            sequence<SREdge> edges;

        };
    };
};
#endif