#ifndef TCNART_MSG_TYPES
#define TCNART_MSG_TYPES

module tcnart_msgs {
  module msg {
    

    enum SensorType {
        SENSOR_TYPE_NONE,
        SENSOR_TYPE_VIDEO_COLOR,
        SENSOR_TYPE_VIDEO_DEPTH,
        SENSOR_TYPE_VIDEO_IR,
        SENSOR_TYPE_TRACKING_POSE,
        SENSOR_TYPE_TRACKING_EYE,
        SENSOR_TYPE_TRACKING_HAND,
        SENSOR_TYPE_TRACKING_BODY,
        SENSOR_TYPE_AUDIO,
        SENSOR_TYPE_IMU_ACCEL,
        SENSOR_TYPE_IMU_GYRO,
        SENSOR_TYPE_IMU_MAG,
        SENSOR_TYPE_MESH_BITSTREAM,
        SENSOR_TYPE_SURFEL
    };


    enum VideoPixelFormat {
      PixelFormat_NV12,
      PixelFormat_RGB24,
      PixelFormat_BGR24,
      PixelFormat_BGRA32,
      PixelFormat_L8,
      PixelFormat_L16
      PixelFormat_RGBA32,
    };

    enum VideoImageCompression {
        CompressionType_Raw,
        CompressionType_Png,
        CompressionType_H26x,
        CompressionType_Zdepth,
        CompressionType_Jpeg
    };

    enum VideoH26xProfile {
        H264Profile_Base,
        H264Profile_Main,
        H264Profile_High,
        H265Profile_Main,
        H26xProfile_None
    };

    enum AudioAACProfile {
        AACProfile_12000,
        AACProfile_16000,
        AACProfile_20000,
        AACProfile_24000,
        AACProfile_None
    };

    enum MarkerType {
      MARKER_TYPE_NONE,
      MARKER_TYPE_ARUCO_MARKER,
      MARKER_TYPE_ARUCO_BOARD,
      MARKER_TYPE_ARUCO_FRACTAL,
      MARKER_TYPE_IR_TARGET
    };

    struct MSGuid {
      uint32 Data1;
      uint16 Data2;
      uint16 Data3;
      uint8 Data4[8];
    };

    struct UUID {
      uint8 uuid[16];
    };



    struct Vector4 {
      double x;
      double y;
      double z;
      double w;
    };

    struct Quaternion {
      double x;
      double y;
      double z;
      double w;
    };

    struct Vector3 {
      double x;
      double y;
      double z;
    };

    struct Vector2 {
      double x;
      double y;
    };

    // column major Matrix 4x4
    struct Matrix4x4 {
      double col0[4];
      double col1[4];
      double col2[4];
      double col3[4];
    };

    struct Matrix4x3 {
      double col0[3];
      double col1[3];
      double col2[3];
      double col3[3];
    };

    struct Matrix3x3 {
      double col0[3];
      double col1[3];
      double col2[3];
    };

    struct RigidTransform {
      Vector3 translation;
      Quaternion rotation;
    };

    struct RigidTransformMapItem {

      uint32 item_id;

      RigidTransform pose;

    };

    struct RigidTransformMap {

      RigidTransform pose;

      sequence<RigidTransformMapItem> poses;

    };

    struct Marker {
      uint32 marker_id;
      Vector3 position;
      float quality; // Normalized 0.0 to 1.0
      boolean visible;
    };

    struct Target {
      uint32 target_id;
      RigidTransform pose;
      float quality; // Normalized 0.0 to 1.0
      sequence<Marker> markers;
      boolean is_tracked; // if enough markers on the tool are visible to track it
    };

    struct Ray {
      Vector3 origin;
      Vector3 direction;
    };

    struct ViewPose {
      Vector3 eye;
      Vector3 target;
      Vector3 up;
    };

    struct Plane {
      Vector3 normal;
      float d;
    };

    struct BoundingBox {
      Vector3 center;
      Vector3 extents;
    };

    struct Frustum {
      Plane plane_near;
      Plane plane_far;
      Plane plane_right;
      Plane plane_left;
      Plane plane_top;
      Plane plane_bottom;
    };

    struct OrientedBox {
      Vector3 center;
      Vector3 extents;
      Quaternion orientation;
    };

    struct Sphere {
      Vector3 center;
      float radius;
    };



  };
};

#endif
