#ifndef TCNART_MSGS_VIDEOSTREAM
#define TCNART_MSGS_VIDEOSTREAM

#include "tcnart_msgs/msg/Types.idl"
#include "std_msgs/msg/Header.idl"

module tcnart_msgs {
  module msg {

    struct VideoStreamMessage {

      std_msgs::msg::Header header;

      RigidTransform pose;

      float camera_focal_length[2];
      float camera_principal_point[2];
      
      float camera_radial_distortion[3];
      float camera_tangential_distortion[2];

      uint64 image_bytes;
      sequence<uint8> image;

    };
  };
};
#endif